# Generated by Django 4.0.4 on 2023-07-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
